# What do want? (atua kailangan sa mongodb)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# How do we want it implemented (unsa kadako himuon?)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/some_new/directory/structure/"
    type: DirectoryOrCreate


#to delete and recreate delete pvc first then pv
#k delete pvc mongo-pvc --grace-period=0 --force